server:
  port: 10000
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://120.77.38.112:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tJpAYDou8rSwC312fVE
      secret-key: MF2Di2RonGMH1YXkPbYCBae1TYNkXq
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
#静态资源访问
#    prefix: /templates/
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**

  redis:
    host: 120.77.38.112
    port: 6379

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    com.atguigu: debug
