spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tJpAYDou8rSwC312fVE
      secret-key: MF2Di2RonGMH1YXkPbYCBae1TYNkXq
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-980926
  application:
    name: gulimall-third-party
server:
  port: 30000